import { TestUtils } from "../utils/TestUtils"

export interface SubtitlesItem {
  autoGenerated: boolean

  /**
   * Language code
   *
   * Example: "en"
   */
  code: string

  /**
   * Mime type of subtitles
   *
   * Example: application/ttml+xml
   */
  mimeType: string

  name: string

  /**
   * Absolute url for subtitles
   *
   * Example: "https://pipedproxy-bom.kavin.rocks/api/timedtext?..."
   */
  url: string
}

export function testSubtitles(subtitles: SubtitlesItem[]) {
  subtitles.forEach(item => testSubtitlesItem(item))
}

export function testSubtitlesItem(subtitlesItem: SubtitlesItem) {
  const { autoGenerated, code, mimeType, name, url } = subtitlesItem

  TestUtils.expectBoolean(autoGenerated)
  TestUtils.expectString(code)
  TestUtils.expectString(mimeType)
  TestUtils.expectString(name)
  TestUtils.expectString(url)
}
