export interface SubtitlesItem {
  autoGenerated: boolean

  /**
   * Language code
   *
   * Example: "en"
   */
  code: string

  /**
   * Mime type of subtitles
   *
   * Example: application/ttml+xml
   */
  mimeType: string

  name: string

  /**
   * Absolute url for subtitles
   *
   * Example: "https://pipedproxy-bom.kavin.rocks/api/timedtext?..."
   */
  url: string
}
